name: RefreshMenu
version: '${project.version}'
main: ru.cwcode.tkach.refreshmenu.RefreshMenu
api-version: 1.16
authors: [ TkachGeek ]
website: cwcode.ru/vk
depend:
  - ProtocolLib
  - CWCommands
  - CWConfig
